# Generated by Django 5.2.8 on 2025-12-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='Internal path (e.g., /dashboard/) or external URL (https://google.com)', max_length=200)),
                ('icon', models.CharField(default='fa-solid fa-link', help_text='FontAwesome class (e.g., fa-solid fa-file)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(help_text='Select user roles that can see this link', related_name='dashboard_links', to='auth.group')),
            ],
            options={
                'verbose_name': 'Dashboard Link',
                'verbose_name_plural': 'Dashboard Links',
                'ordering': ['order'],
            },
        ),
    ]
