# Generated by Django 5.2.8 on 2025-12-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardlink',
            name='description',
            field=models.CharField(blank=True, help_text='Short description displayed on the dashboard card', max_length=255, null=True),
        ),
    ]
