# Generated by Django 5.2.8 on 2025-12-06 12:05

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Error Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
            ],
            options={
                'verbose_name': 'Error Code',
                'verbose_name_plural': 'Error Codes',
                'db_table': 'error_codes',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='File Name')),
                ('original_url', models.CharField(max_length=1200, unique=True, verbose_name='Original URL')),
                ('secondary_url', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Secondary URL')),
                ('thumbnail_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Thumbnail URL')),
                ('thumbnail_drive', models.CharField(blank=True, max_length=500, null=True, verbose_name='Thumbnail Drive')),
                ('media_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Media Type')),
                ('post_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Post URL')),
                ('filesize_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Filesize Bytes')),
                ('filesize', models.CharField(blank=True, max_length=50, null=True, verbose_name='Filesize')),
                ('post_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Post Title')),
                ('post_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Post ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('downloaded', models.BooleanField(default=False, verbose_name='Downloaded')),
                ('synced', models.BooleanField(default=False, verbose_name='Synced')),
                ('error_code', models.IntegerField(default=0, verbose_name='Error Code')),
                ('starred', models.BooleanField(default=False, verbose_name='Starred')),
                ('drive_file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Drive File ID')),
                ('drive_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Drive ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'db_table': 'media_files',
            },
        ),
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Model Name')),
                ('suffix', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suffix')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('picture', models.CharField(blank=True, max_length=512, null=True, verbose_name='Picture')),
                ('search_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Search Text')),
                ('folder', models.IntegerField(blank=True, null=True, verbose_name='Folder')),
                ('uploads_folder', models.IntegerField(blank=True, null=True, verbose_name='Uploads Folder')),
                ('files_count', models.IntegerField(blank=True, null=True, verbose_name='Files Count')),
                ('drive_no', models.IntegerField(default=0, verbose_name='Drive Number')),
                ('drive_folder_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Drive Folder ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
            ],
            options={
                'verbose_name': 'Model Name',
                'verbose_name_plural': 'Model Names',
                'db_table': 'model_names',
            },
        ),
        migrations.CreateModel(
            name='SubredditList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit_name', models.CharField(max_length=255, verbose_name='Subreddit Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('subreddit_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subreddit URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
            ],
            options={
                'verbose_name': 'Subreddit',
                'verbose_name_plural': 'Subreddits List',
                'db_table': 'subreddits_list',
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video Category',
                'verbose_name_plural': 'Video Categories',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Folder Name')),
                ('files_count', models.IntegerField(default=0, verbose_name='Files Count')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='media_manager.folder', verbose_name='Parent Folder')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'db_table': 'folders',
            },
        ),
        migrations.CreateModel(
            name='MediaStat',
            fields=[
                ('media_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='media_manager.mediafile', verbose_name='Media File')),
                ('total_views', models.IntegerField(default=0, verbose_name='Total Views')),
                ('duration', models.IntegerField(default=0, verbose_name='Duration')),
                ('last_visited', models.DateTimeField(blank=True, null=True, verbose_name='Last Visited')),
            ],
            options={
                'verbose_name': 'Media Stat',
                'verbose_name_plural': 'Media Stats',
                'db_table': 'media_stats',
            },
        ),
        migrations.AddField(
            model_name='mediafile',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='media_manager.folder'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='media_manager.modelname'),
        ),
        migrations.CreateModel(
            name='ModelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField(blank=True, null=True, verbose_name='Story')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('associated_models', models.ManyToManyField(blank=True, related_name='records', to='media_manager.modelname', verbose_name='Models')),
            ],
            options={
                'verbose_name': 'Model Record',
                'verbose_name_plural': 'Model Records',
                'db_table': 'model_records',
            },
        ),
        migrations.AddField(
            model_name='mediafile',
            name='subreddit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='media_manager.subredditlist'),
        ),
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Video Title')),
                ('original_url', models.CharField(max_length=2000, unique=True, verbose_name='Original URL')),
                ('thumbnail_url', models.CharField(blank=True, max_length=1200, null=True, verbose_name='Thumbnail URL')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_manager.videocategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Video Link',
                'verbose_name_plural': 'Video Links',
                'db_table': 'video_links',
            },
        ),
    ]
