# Generated by Django 5.2.8 on 2025-12-02 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='Accounts/profile_images/default.jpg', null=True, upload_to='Accounts/profile_images', verbose_name='Profile Picture')),
                ('cover_picture', models.ImageField(blank=True, default='Accounts/cover_images/_default.jpg', null=True, upload_to='Accounts/cover_images', verbose_name='Cover Picture')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True)),
                ('headline', models.CharField(blank=True, max_length=80, null=True)),
                ('bio', models.TextField(blank=True, null=True, verbose_name='About me')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
