# Generated by Django 5.2.9 on 2025-12-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
